### ISSUE TITLE
fix_start_bit possible bug

### ISSUE THREAD

**Issue by FrancescoScappatura** [howerj/dbcc#1]
Hi howerj, first of all thanks for your code.

static unsigned fix_start_bit(bool motorola, unsigned start)
{
	if(motorola)
		start = (8 * (7 - (start / 8))) + (start % 8);
	return start;
}

What about this functions? Shouldn't it return start-(signal->bit_length)?

**Comment by howerj** [comment]
Hmm, I should probably get around to looking at this sometime...

**Comment by chentyjpm** [comment]
> Hmm, I should probably get around to looking at this sometime...

i fix it in pull requrest please check it ^_^

**Comment by howerj** [comment]
Thanks! That's merged now.
