### ISSUE TITLE
Translation to physical unit

### ISSUE THREAD

**Issue by xR3b0rn** [howerj/dbcc#12]
This dbc signal:
`SG_ SIGNAL : 12|12@1- (0.5,0) [-1023.5|1023.5] "Nm"`  
Leads to this code:
```
rval *= 2.000000;
if((rval >= -1023.500000) && (rval <= 1023.500000)) {
```
in terms of the translation to the physical unit.
In my case this is defentetly wrong. canntools is doing it right so the dbc File must be correct and this must be a bug. 

Maybe there are two kinds of translation:
- Translation by reciprocal
- Translation by value

And for now the program handels only the first one? - I don't know.

For me I fixed this by replacing 
`fprintf(o, "\trval *= %f;\n", 1.0 / sig->scaling);`
with:
`fprintf(o, "\trval *= %f;\n", sig->scaling);`
in 2c.c:237.

**Comment by howerj** [comment]
I think you're right, I'll change this. I have no way of checking what is correct in different CAN tools, as I don't have access to any, any more.
