### ISSUE TITLE
size_t for message_count

### ISSUE THREAD

**Issue by martonmiklos** [howerj/dbcc#24]
https://github.com/howerj/dbcc/blob/ce968d8132b4f7705450912bca1cebae79964421/can.h#L70

Is there any reason why here int was used not size_t like here:
https://github.com/howerj/dbcc/blob/ce968d8132b4f7705450912bca1cebae79964421/can.h#L63

**Comment by howerj** [comment]
No there isn't. I've fixed it in the latest commit. Cheers!
