### ISSUE TITLE
Documentation on Conversion of 8 bytes to uint64

### ISSUE THREAD

**Issue by jimmyw404** [howerj/dbcc#28]
Thank you for the creation of this library, I have found it very useful.

When examining the documentation of how to convert between an 8 byte array and a uint64 variable, unless I'm mistaken the 8th byte shift is incorrect:
```
static uint64_t u64_from_can_msg(const uint8_t m[8]) {
	return ((uint64_t)m[7] << 54) | ((uint64_t)m[6] << 48) | ((uint64_t)m[5] << 40) | ((uint64_t)m[4] << 32) 
		| ((uint64_t)m[3] << 24) | ((uint64_t)m[2] << 16) | ((uint64_t)m[1] << 8) | ((uint64_t)m[0] << 0);
}

static void u64_to_can_msg(const uint64_t u, uint8_t m[8]) {
	m[7] = u >> 54;
	m[6] = u >> 48;
	m[5] = u >> 40;
	m[4] = u >> 32;
	m[3] = u >> 24;
	m[2] = u >> 16;
	m[1] = u >>  8;
	m[0] = u >>  0;
}
```

It should be 56 (as in, 8 more than 48 and 8 less than 64) for both of these, ex:
(uint64_t)m[7] << 56
m[7] = u >> 56;

**Comment by howerj** [comment]
Cheers for that! Silly mistake!
