### ISSUE TITLE
dbcc.xsd not valid because of typo

### ISSUE THREAD

**Issue by Delphin-smarx** [howerj/dbcc#29]
A space character in <xs:maxInclusive value="3221225472 "/> leads xml schema parsers to throw an error. ( https://github.com/howerj/dbcc/blob/master/dbcc.xsd#L108 )

```
<xs:simpleType name="can-id">
	<xs:restriction base="xs:integer">
		<xs:minInclusive value="0"/>
		<xs:maxInclusive value="3221225472 "/>
		<!-- Maximum ID should be '536870911', some DBCs do not abide by this -->
	</xs:restriction>
</xs:simpleType>
```

Fixed by deleting the space behind "3221225472".

**Comment by howerj** [comment]
Cheers for that! I'm going to need a schema for my schema, but when would the madness end?
