### ISSUE TITLE
can it convert CanFD.dbc file convert .h header file?

### ISSUE THREAD

**Issue by chendanyuan** [howerj/dbcc#34]
Hello howerj
I think this can only be used on standard can, is it correct ? 
can it or do you have any plans on CanFD version ?

**Comment by howerj** [comment]
Hello, sorry for the late reply,

This program can only deal with standard CAN DBC files, I currently have no plans to support CanFD (the increased data
size means I would have to drastically change this program).

Thanks,
Richard Howe
