### ISSUE TITLE
Hide breaking changes behind feature flag

### ISSUE THREAD

**Issue by howerj** [howerj/dbcc#41]
Prompted by issue https://github.com/howerj/dbcc/pull/40, which has now been merged onto the branch feature/better-enums it would be wise to hide changes behind feature flags for any new breaking changes from now on, by either specifying a version (to get that versions behaviour), or by enabling a specific flag. The details need working out.

**Comment by warrickw** [comment]
I've had a go over here: https://github.com/howerj/dbcc/pull/42

**Comment by howerj** [comment]
Going to close this now it's all merged and stuff
