### ISSUE TITLE
Something wrong with generating the message ID of extended frame

### ISSUE THREAD

**Issue by ChenShaomin** [howerj/dbcc#43]
My message is an extended frame with ID 0xCC0016E and the generated C code ID is 0x8CC0016E. 
The 32nd bit of the ID of each extended frame becomes 1.

**Comment by howerj** [comment]
I haven't been able to reproduce this issue (I edited one of the projects example DBC files with that ID and it worked fine), could you post the following:

* A minimal example DBC file containing the problem
* Which compiler you are using
* What operating system you are running
* The output of "./dbcc -V"

Thanks
