### ISSUE TITLE
Feature request: Generating enum for Frame ID.

### ISSUE THREAD

**Issue by FZGabriel** [howerj/dbcc#46]
Hi! 

I sometimes need to use CAN ID in my code.
Currently, the generated code doesn't provide any way to use the CAN ID.

Having at the top of the generated header file an enum would be useful.
Something like:
```C
typedef enum {
    CAN_ID__XCP_Request_All = 0x200
    CAN_ID__XCP_Request_Ivt = 0x201
    CAN_ID__XCP_Response_Ivt = 0x202
} MyDBC_CAN_ID_t;
```

Thanks again for your work!

**Comment by howerj** [comment]
That seems like it might be useful, I do not have much time this week to do things, but I will eventually get around to sorting things.
