### ISSUE TITLE
C-Code generation signal range check

### ISSUE THREAD

**Issue by xR3b0rn** [howerj/dbcc#8]
The C-Code generator generates wrong code for range check. This code is generated:
if((rval <= -1023.500000) && (rval >= 1023.500000)) {
But the genrator should generate:
if((rval >= -1023.500000) && (rval <= 1023.500000)) {

To fix this, just change 
fprintf(o, "\tif((rval <= %f) && (rval >= %f)) {\n", sig->minimum, sig->maximum);
in file 2c.c:239 to:
fprintf(o, "\tif((rval >= %f) && (rval <= %f)) {\n", sig->minimum, sig->maximum);

**Comment by howerj** [comment]
Thanks! That's a quick fix.
